fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"

# profile module layout, default include ntp module
    mcollective: "https://github.com/puppet-community/puppet-mcollective.git"
    datacat: "https://github.com/richardc/puppet-datacat.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    rspec_monitor: "git://github.com/pgomersbach/test-rspec_monitor.git"
    rabbitmq: "https://github.com/puppetlabs/puppetlabs-rabbitmq.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt"
    staging: "https://github.com/nanliu/puppet-staging"

  symlinks:
    profile_mcollective: "#{source_dir}"
